Fast-64/fast64

README.md
fast64_internal/oot/README.md
fast64_internal/sm64/README.md

https://github.com/Dragorn421/fast64/blob/updatereadme/README.md
https://github.com/Dragorn421/fast64/blob/updatereadme/fast64_internal/sm64/README.md
https://github.com/Dragorn421/fast64/blob/updatereadme/fast64_internal/oot/README.md
this first PR is also a good occasion to discuss about merging PRs: I think we should squash merge to keep the history as clean as can be and avoid "wip commits"/broken revisions. also makes it easier to git blame

Mention forked from bitbucket and fix links

---

fast64_internal/oot/c_writer/oot_level_c.py
fast64_internal/oot/oot_f3d_writer.py

- Add 1 to sequence number in export so that in-game sequence number is as expected
- Add two optional custom gSPSegment addresses to material editor

Custom gSPSegment and improve sequence numbering

---

fast64_internal/oot/c_writer/oot_level_c.py
fast64_internal/oot/oot_level_classes.py

Write OoT scene lighting data as hex

---

fast64_internal/oot/c_writer/oot_scene_table_c.py

[OoT] Missing one "Scene" not changed to "SceneTableEntry" causing exporter to write Scene in z_scene_table.c

---

fast64_internal/sm64/sm64_texscroll.py
fast64_internal/sm64/sm64_utility.py

Just uses `os.path.exists` to determine where the file is!

Allow memory.c to be in boot/ or game/

---

fast64_internal/sm64/sm64_geolayout_writer.py

`saveStaticModel` can return `None`, so I put a truthiness check here!

[SM64] Ensure that objects have polygons while exporting

---

fast64_internal/utility.py

the logic is a lot more "positive" now. i check if something _should_ be instanced instead of shouldn't be instanced

refactor and cleanup store_original_meshes

---

__init__.py

explicitly import SM64_Panel

---

fast64_internal/sm64/sm64_objects.py

This u32 value is almost always used as 4 different params, so this is just a little convenience feature for editing each param quickly.

Added ability to set bparams individually

---

fast64_internal/sm64/sm64_geolayout_writer.py

put a TODO comment so that exporting isn't broken.

HOTFIX: set lastMaterialName to None

---

fast64_internal/oot/c_writer/oot_level_c.py

This fixes a bug that I introduced with the room rom segment extern change, whoops :V

OoT Scene Export Hotfix

---

fast64_internal/f3d/f3d_material.py

Hey Zelda people can any of you test some OOT exports with this branch?

Cross compatibility for Blender 3.0

---

fast64_internal/f3d/f3d_enums.py
fast64_internal/f3d/f3d_material.py

Thanks to @sauraen for helping with these

Make blender input names clearer

---

fast64_internal/oot/oot_f3d_writer.py

Minor typo fix in a rarely-encountered codepath in skeleton export.

Fix OoT skeleton bug

---

fast64_internal/oot/oot_skeleton.py

Add defines for the limbs of a skeleton to the header, for example:
```
#define YOURMESH_ROOT_POS_LIMB 0
#define YOURMESH_ROOT_ROT_LIMB 1
#define YOURMESH_SOMETHING_LIMB 2
#define YOURMESH_FOO_LIMB 3
#define YOURMESH_NUM_LIMBS 4
```

Add limb name defines

---

fast64_internal/sm64/sm64_objects.py

@Bitlytic can you check this too? we need to add you into this org

Made bparams an individual toggle and improved/fixed migration

---

fast64_internal/oot/oot_collision.py
fast64_internal/oot/oot_utility.py

Addresses #88
Before:
```c
CollisionPoly collision_polygons[] = {
{ 0x0000, 0x0000, 0x0001, 0x0002, -0x8000, 0x0000, 0x0000, 0xf060 },
{ 0x0000, 0x0000, 0x0002, 0x0003, -0x8000, 0x0000, 0x0000, 0xf060 },
{ 0x0000, 0x0003, 0x0002, 0x0004, 0x0000, 0x0000, -0x8000, 0xf060 },
{ 0x0000, 0x0003, 0x0004, 0x0005, 0x0000, 0x0000, -0x8000, 0xf060 },
{ 0x0000, 0x0005, 0x0004, 0x0006, 0x7fff, 0x0000, 0x0000, 0xd120 },
{ 0x0000, 0x0005, 0x0006, 0x0007, 0x7fff, 0x0000, 0x0000, 0xd120 },
{ 0x0000, 0x0007, 0x0006, 0x0001, 0x0000, 0x0000, 0x7fff, 0xf060 },
{ 0x0000, 0x0007, 0x0001, 0x0000, 0x0000, 0x0000, 0x7fff, 0xf060 },
{ 0x0000, 0x0003, 0x0005, 0x0007, 0x0000, -0x8000, 0x0000, 0xfc18 },
{ 0x0000, 0x0003, 0x0007, 0x0000, 0x0000, -0x8000, 0x0000, 0xfc18 },
{ 0x0000, 0x0004, 0x0002, 0x0001, 0x0000, …
```

[OoT] Export collision normals as floats using `COLPOLY_SNORMAL` macro

---

fast64_internal/f3d/f3d_writer.py

Add object name to "object has no materials" error

---

fast64_internal/f3d/f3d_writer.py

I'm sorry but my editor trimmed the whitespace 😢

Fixed calculating tex line size

---

fast64_internal/f3d/f3d_enums.py
fast64_internal/f3d/f3d_material_presets.py
fast64_internal/f3d/f3d_material_settings.py

Black-format the three simplest files in `fast64_internal/f3d/`

Black-format 1

---

fast64_internal/oot/oot_collision.py

Not pointing fingers but reviewers of #100 let this slip through, smh my head

[OoT] Fix camera export regression

---

fast64_internal/oot/c_writer/oot_level_c.py

Format/cleanup oot_level_c.py

---

fast64_internal/oot/c_writer/oot_level_c.py
fast64_internal/oot/oot_collision.py
fast64_internal/oot/oot_level.py
fast64_internal/oot/oot_level_classes.py
fast64_internal/oot/oot_level_writer.py
fast64_internal/oot/oot_operators.py
fast64_internal/oot/oot_skeleton.py
fast64_internal/oot/oot_utility.py

(normally merge this, no squash)
Then I merge fast64/V5 into thecozies/V5 and all is happy (until the next commit on fast64/main :morphon:)

Merge fast64/main into fast64/V5

---

fast64_internal/sm64/sm64_anim.py

Added support for vanilla animation tables.

Support for vanilla animation tables

---

__init__.py

Once merged, tag the version (githb releases), then V5 yay
EDIT: githb

Bump fast64/main version to 1.0.1

---

fast64_internal/oot/oot_collision.py

This file is formatted in fast64/V5 but not fast64/main and it worsens the conflicts

Format oot_collision.py

---

fast64_internal/oot/oot_scene_room.py

This file is formatted in fast64/main but not fast64/V5 and it worsens the conflicts

Format oot_scene_room.py

---

README.md
__init__.py

I decided to update the description too since SM64 isn't the only supported game now

Updated minimum version in the readme + plugin description update

---

fast64_internal/oot/c_writer/oot_scene_folder.py
fast64_internal/oot/c_writer/oot_spec.py
fast64_internal/oot/oot_cutscene.py
fast64_internal/oot/oot_spline.py

This PR only applies Black on those files:
```
oot/c_writer/oot_spec.py
oot/c_writer/oot_scene_folder.py
oot/oot_cutscene.py
oot/oot_spline.py
```
Those files are what's not formatted yet in the OoT folder, I didn't do `` oot_actor.py`` since this is modified in an opened PR, also skipped `` sceneDirectoryParser.py``  and `` oot_parse.py`` since those are unused files that gets deleted in PR 95

[OoT] Format what's left (3 exceptions)

---

fast64_internal/f3d/f3d_material.py
fast64_internal/f3d/f3d_parser.py
fast64_internal/f3d/f3d_writer.py

Input only shows up if LOD is enabled.
Here's an example of it working:
https://user-images.githubusercontent.com/79979276/195990966-093db2e4-428b-457e-90bf-2a671de5f59e.mp4

Added LOD level option

---

fast64_internal/f3d/f3d_material.py

Its a small performance boost but it can add up.

[Performance] mute unused texture nodes

---

fast64_internal/f3d/f3d_gbi.py
fast64_internal/f3d/f3d_material.py

i also black formatted f3d_material.py and it caught a few things outside of my change

[SM64] tex scrolling adjustments

---

fast64_internal/f3d/f3d_gbi.py
fast64_internal/f3d/f3d_writer.py

cleaned up string formatting in f3d_gbi
removed useless syncs in material generation
these changes are also in the KCS_main PR, but this one was made separately in order to break apart changes

GBI Macro Refactoring + F3D Sync Optimization

---

fast64_internal/oot/scene/exporter/to_c/spec.py

`#include "include/config.h"` and other includes at the top of the spec will be preserved when fast64 modifies the spec. Or rather, all includes which were present anywhere in the original file will be re-added at the top of the new file when it is written. This is required for HackerOOT.

Added feature to preserve include(s) at the top of spec for HackerOOT

---

fast64_internal/oot/oot_actor.py
fast64_internal/oot/oot_level_classes.py
fast64_internal/oot/oot_scene_room.py
fast64_internal/oot/oot_texture_array.py
fast64_internal/oot/oot_utility.py
fast64_internal/oot/scene/exporter/to_c/scene_commands.py

This PR fixes an issue found by Dragorn, the UI had an issue where object ID custom wouldn't display (also I used Black, hence the extra files)

[OoT] Fix for custom Object IDs (and formatted some files)

---

fast64_internal/oot/oot_level_writer.py

Changes:
- Added custom path option for decomp mode, the remove operator grays out if the path doesn't exists
- Added a box for HackerOoT export options to make it less confusing

[OoT] Improvements and fixes for scene exporter panel

---

fast64_internal/utility_anim.py

Needs to be in-function to avoid circular import
stupid imports <img src="https://www.streamscheme.com/wp-content/uploads/2020/04/dansgame-1.png" height="24" alt="DansGame">
See also: issue on discord

Fix missing import

---

fast64_internal/sm64/sm64_geolayout_writer.py

fixes issue with area object being none during object geo layout exports

Mat Bleed Geo Layout Fix

---

fast64_internal/f3d/f3d_material.py

there are no more possible key errors that could occur at this point. gamebun had a material that didnt even have combiner2 or rdp_settings somehow so i just made sure to verify every possible key here before copying

key check the remainder of f3d mat settings for upgrading super ultra old materials

---

fast64_internal/f3d/f3d_texture_writer.py
fast64_internal/utility.py

Fixes uncessary renamings for file names which makes using vanilla assets much better.

Png exporting hotfixes

---

fast64_internal/oot/oot_anim.py
fast64_internal/oot/oot_collision.py
fast64_internal/oot/oot_level_writer.py
fast64_internal/oot/oot_model_classes.py
fast64_internal/oot/oot_texture_array.py
fast64_internal/oot/oot_upgrade.py
fast64_internal/oot/skeleton/constants.py
fast64_internal/oot/spline/properties.py

I randomly found a small issue inside ``addFlipbookWithRepeatCheck()`` and I wanted to format OoT files with Black before it starts to get funny

[OoT] Format with Black and small fix

---

fast64_internal/f3d/f3d_material.py
fast64_internal/sm64/sm64_geolayout_bone.py
fast64_internal/sm64/sm64_geolayout_parser.py
fast64_internal/sm64/sm64_geolayout_utility.py
fast64_internal/sm64/sm64_geolayout_writer.py

This PR adds support for Blender 4.0 API changes.

Add support for Blender 4.0

---

fast64_internal/sm64/sm64_f3d_writer.py
fast64_internal/sm64/sm64_geolayout_writer.py

Some garbled F3D classes in a SM64 binary export codepath. Looks like this was updated in some previous PR and nobody ran this since.

Hotfix for Bloxifilmz

---

fast64_internal/f3d/f3d_parser.py

Fix sm64 geolayout imports

---

fast64_internal/oot/cutscene/motion/panels.py

Fix OoT UI showing in SM64

---

fast64_internal/sm64/sm64_anim.py

I tested this method in my own branches, it works and it fixes translation issues (see https://discord.com/channels/874816709855440926/1196963740705357894), along with being faster

[SM64] - Fix animation translation

---

fast64_internal/f3d/f3d_material.py
fast64_internal/f3d/f3d_material_presets.py

Fix preset in new materials, consolidate applying presets

---

fast64_internal/oot/scene/exporter/to_c/scene_table_c.py
fast64_internal/oot/scene/exporter/to_c/spec.py

also this adds a fix for a possible issue if there's consecutives preprocessor directives

Fixed scene table capitalization issue

---

fast64_internal/oot/cutscene/classes.py
fast64_internal/oot/cutscene/importer/classes.py

fixes issues with actor cues, light settings and the ``CS_FLOAT`` thing, not entirely satisfied but it works™

[OoT] Fix cutscene import issues

---

fast64_internal/sm64/sm64_level_writer.py

Add `LOAD_VANILLA_OBJECTS` cmd to support PR https://github.com/HackerN64/HackerSM64/pull/796

[SM64] add LOAD_VANILLA_OBJECTS to list of segment loads cmds

---

fast64_internal/sm64/sm64_geolayout_writer.py

Wrong argument was being passed in

[SM64] Fix saveSkinnedMeshByMaterial

---

fast64_internal/f3d/f3d_writer.py

Check for f3dex3 GBI before for writing cel levels, and remove the icon="Error" keyword argument that was causing the exception raise to fail

[F3D] Fixed two issues with ex3 cel shading

---

fast64_internal/f3d/f3d_material.py

Without checking if warnings are needed this will attempt to draw in the world rdp defaults panel

[F3D] Fix small issue with world defaults UI

---

fast64_internal/f3d/f3d_material.py
fast64_internal/f3d_material_converter.py
fast64_internal/sm64/settings/properties.py
fast64_internal/sm64/sm64_objects.py
fast64_internal/sm64/tools/properties.py
fast64_internal/utility.py

Makes upgrade code cleaner and easier to read while adding safety checks, handaling popping, never setting if the old prop didn´t exist, cases where there can be multiple props, changed enum definitions and the dreaded forced base 16 int string
Fixes random invalid decomp path exceptions in sm64

[Codebase] Small generalized upgrade function

---

fast64_internal/sm64/sm64_level_writer.py

[SM64] remove " after ultra64 include

---

fast64_internal/oot/oot_utility.py

found by @Reonu, it never happened to me when testing with my usual test blend :)

[OoT] Fixed room actors being duplicated

---

fast64_internal/f3d/f3d_gbi.py

If any flag was 0 this would fail

[F3D] Fix binary exports

---

fast64_internal/sm64/sm64_level_writer.py

I take responsibility for assuming my main merge was correct, sorry
Scut changed macro to function in the combined exporter pr which was merged first

[SM64] Fix string to macros regression

---

fast64_internal/oot/oot_texture_array.py

[OoT] Fix #404 - Link eyes/mouths import

---

fast64_internal/oot/animation/importer/functions.py

[OoT] Fix #291 - Link anim import

---

fast64_internal/oot/f3d/operators.py

Fixes #384 (loosely, at least it doesn't error and produces a dlist)
See the issue for details

[OoT] Fix #384 - Custom path DL imports

---

fast64_internal/f3d/f3d_material.py

Fixes the auto picker trying to run in material upgrades

[F3D] Don´t update format to reload node values

---

fast64_internal/sm64/settings/constants.py
fast64_internal/sm64/sm64_geolayout_classes.py
fast64_internal/sm64/sm64_objects.py
fast64_internal/sm64/sm64_utility.py

Objective: Add a hackersm64 option for this fast64 release that hacker can safely use in its repo settings file, this pr implements no new features and no new functionality besides one safety check for the refresh version being in the function map, it can safely be merged with minimal testing as to not delay the release
Things to test:
1. searching a behavior in the object empty ui
2. exporting a level with a simple object and checking if the bhv is correct
3. exporting mario and checking if his functions are correct

[SM64] Future proof release for future hacker exclusive features

---

fast64_internal/f3d/f3d_parser.py
fast64_internal/oot/oot_model_classes.py
fast64_internal/oot/skeleton/importer/functions.py

Remove game requirement for importMesh, mk64 uses it.

[F3D/MK64] Fix #366 regression

---

fast64_internal/f3d_material_converter.py

Fixes update callbacks not running

[F3D] Quick BSDF converter fix

---

fast64_internal/sm64/sm64_objects.py

recent regression caused by me, yay

[SM64] show custom export path without save textures

---

fast64_internal/oot/exporter/collision/__init__.py
fast64_internal/oot/exporter/collision/polygons.py

possibly the most important bug fix of all time???

Fix bug where water conveyors set COLPOLY_IS_FLOOR_CONVEYOR

---

fast64_internal/oot/actor/properties.py
fast64_internal/oot/data/xml/ActorList.xml

found by @Reonu, also this adds a collectible entry for "item none"

[OoT] Fixed UI issue when an actor has no type

---

fast64_internal/oot/data/xml/EnumData.xml

decomp issues I found while watching cutscenes

[OoT] Updated `EnumData.xml` (fixes some cutscene import issues)

---

fast64_internal/f3d/f3d_gbi.py
fast64_internal/f3d/f3d_texture_writer.py

Prevents duplicates, causing the behavior seen in this issue https://discord.com/channels/874816709855440926/1373127651283439636

[F3D] Use set for image and pal dependencies

---

fast64_internal/f3d/f3d_enums.py

[F3D] Fix cycle 2 NOOP identifier

---

fast64_internal/oot/exporter/decomp_edit/__init__.py
fast64_internal/oot/exporter/decomp_edit/scene_table.py
fast64_internal/oot/exporter/scene/__init__.py
fast64_internal/oot/exporter/scene/general.py
fast64_internal/oot/scene/properties.py

This adds a string property to let users write the name of the title card to use, by default the value is set to `none` and it will export `none` if it's empty, ~~also I added the missing includes~~

[OoT] Add basic title cards support

---

fast64_internal/oot/__init__.py
fast64_internal/oot/animation/exporter/classes.py
fast64_internal/oot/collision/exporter/to_c/collision.py
fast64_internal/oot/cutscene/operators.py
fast64_internal/oot/exporter/scene/__init__.py
fast64_internal/oot/skeleton/exporter/functions.py

https://github.com/zeldaret/oot/pull/2518 will be merged soon and with it headers will change from "z64xxx.h" to "xxx.h"
This PR deals with that change

[OoT] Fix includes for z64 prefix removal

---

fast64_internal/f3d/f3d_bleed.py
fast64_internal/f3d/f3d_gbi.py
fast64_internal/f3d/f3d_writer.py
fast64_internal/sm64/sm64_f3d_writer.py
fast64_internal/sm64/sm64_geolayout_classes.py
fast64_internal/sm64/sm64_geolayout_writer.py

Also rewrite the code to do it all in one go because ew wtf was that old code

[SM64] Make switch material override stackable and apply layer reverts

---

fast64_internal/utility.py

Discovered while importing adult link
Now why does this code even run in that case, I have no idea

Fixup 565 normal import

---

fast64_internal/z64/exporter/scene/__init__.py
fast64_internal/z64/exporter/scene/actors.py
fast64_internal/z64/importer/actor.py
fast64_internal/z64/importer/scene_header.py

this fixes issues related to latest decomp changes, also this change the display type of entrance actors so it shows as cones (same as when you create a new scene with the button)

[OoT] Fix scene command issues

---

fast64_internal/f3d/f3d_material.py

Should at the very least fix this running without fast64 enabled

Try to do append load post on register and remove it on unregister
