- fast64_internal/oot/oot_scene_room.py
- fast64_internal/oot/oot_utility.py
Most operators / GUI code for cutscene editing was hard-coded to use only the main scene header. Adding commands to cutscenes in other headers would actually add them to the cutscene in the main header, and there was no way to add or edit commands in other headers. This has been fixed. Basic cases of editing and exporting multiple cutscenes in one scene have been tested and work.
> Fixed cutscene editing only for primary scene header

- fast64_internal/f3d/f3d_gbi.py
- fast64_internal/f3d/f3d_material.py
This change allows SetTileSize scrolling to go at different intervals. One benefit of this would be having a 32x64 sized texture UV mapped to half of it (32x32), and every so often scroll S by 32, and you'd have yourself a simple animation! Or if you have scroll set to 1, this could allow you to have slower scrolling although it'd be choppier the longer the interval.
https://user-images.githubusercontent.com/79979276/128582153-0adea55a-bf18-45b5-b577-88fc79f0d3e3.mp4
> Added interval for STS Scrolling

- fast64_internal/f3d/f3d_material.py
Set min and max to be the highest possible min/max values. Kept the soft_min and soft_max into normal usage bounds.
> Extend max/min of STS Scrolling amount

- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_spline.py
- fast64_internal/sm64/sm64_objects.py
- fast64_internal/sm64/sm64_spline.py
As the title says. Somebody reached out to me about this bug. If they deleted a point they couldn't export splines and would get a `NoneType has no attribute points` error. This error could be bypassed by making sure to select any random point after deleting a point. So my fix is just using the first spline instead of the active spline, and the export has the same output as before (tested against multiple splines in the same export).
> fixed bug where not having a point selected would prevent splines from being exported

- fast64_internal/oot/c_writer/oot_scene_table_c.py
The OoT exporter broke with the [latest ](https://github.com/zeldaret/oot/commit/7551dc2b71f7c6587f96c498cbd62cfd05aa292c) commit of decomp that changed "Scene gSceneTable" to "SceneTableEntry gSceneTable"
> Fixed the OoT exporter

- fast64_internal/f3d/f3d_writer.py
- fast64_internal/sm64/sm64_f3d_writer.py
- fast64_internal/sm64/sm64_geolayout_writer.py
- fast64_internal/sm64/sm64_level_writer.py
Like basic F3D settings, all `save textures as PNG` toggles are just in the F3D menu as a global setting (helps prevent people from accidentally pressing it)
> Have all exports use global 'save textures as PNG'

- .gitignore
- README.md
- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/operators.py
- fast64_internal/sm64/sm64_geolayout_classes.py
- fast64_internal/sm64/sm64_geolayout_writer.py
- fast64_internal/sm64/sm64_level_writer.py
- fast64_internal/sm64/sm64_objects.py
- fast64_internal/utility.py
Regarding the number of changes:
I enabled "Remove trailing whitespace" in VSCode... There is a TON of trailing whitespace throughout this repo so you may want to disable viewing whitespace changes when reviewing!
Instancing:
In a nutshell, this allows people to use Alt D to create object links, and those links will be exported as the same displaylist. Its a bit tricky because all transformations need to happen in the GeoLayout itself, instead of applying all transformations. This needed to happen in order to get these custom geolayout commands to work, since applying their transformations would break the intended transformation.
Custom Geolayout Commands:
Before this change, there were only a small handful of geolayout commands you could use with objects, while armatures were a low more …
> Custom geo commands and object instancing in SM64 Object exporting

- fast64_internal/sm64/sm64_geolayout_writer.py
before, extra geolayout nodes were added if rotations had an axis angle of `>0.00001`, resulting in useless rotate bones if the rotation would be computed to 0, 0, 0 anyways. so instead i do the same rotation check as object exports, and use the function `isZeroRotation`
> SM64 check for rotation via isZeroRotation

- fast64_internal/sm64/sm64_level_writer.py
- fast64_internal/sm64/sm64_objects.py
this change adds various areas in a levelscript where you can add any sort of code that will stay in that spot
```c
/* FAST64KEEP INCLUDES */
put whatever you want in here
/* FAST64END INCLUDES */
```
This makes it so that anything thats not covered by Fast64 (or just custom in general) doesn't get overwritten when exporting levels. A more generic solution could be cool to eventually implement... (e.g. keep anything between `/* FAST64KEEP BLOCK */` to `/* FAST64END BLOCK */`, but a lot of conflicts could come out of this, so I think its better to be specific for now)
> Added ability to ignore blocks of code in level scripts

- fast64_internal/sm64/sm64_geolayout_bone.py
- fast64_internal/utility.py
People have been setting object scale's to massive values, causing exported objects to loose a ton of precision. So now scaling is _not_ applied by default, and objects are only instanced if there is > 1 user, and I added an option to specifically scale in the `GeoLayout`. Just in case people would want that (like for adding extra precision).
> [SM64] Apply scale by default and add option to skip applying scale

- __init__.py
- fast64_internal/__init__.py
- fast64_internal/f3d/f3d_parser.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/oot/__init__.py
- fast64_internal/oot/oot_anim.py
- fast64_internal/oot/oot_collision.py
- fast64_internal/oot/oot_f3d_writer.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_operators.py
- fast64_internal/oot/oot_skeleton.py
- fast64_internal/panels.py
- fast64_internal/sm64/__init__.py
- fast64_internal/sm64/sm64_anim.py
- fast64_internal/sm64/sm64_collision.py
- fast64_internal/sm64/sm64_f3d_parser.py
- fast64_internal/sm64/sm64_f3d_writer.py
- fast64_internal/sm64/sm64_geolayout_parser.py
- fast64_internal/sm64/sm64_geolayout_writer.py
- fast64_internal/sm64/sm64_level_writer.py
I added property groups for SM64/OOT/General Settings! We should try to migrate over to using these props. I started migration in SM64 by having the C/binary/insertable binary option be in the main file settings. I also have functions in place for migrating over previously chosen options.
Panel base classes! There are base OOT and SM64 panels, they both use the `poll` method to only show if the respective game is selected in the main Fast64 tab.
(note: OOT/SM64 Tabs hidden if not the selected game)
___
___
Everything defaults to being closed, except for file settings
___
___
Like OOT, everything defaults closed except for the top two panels. The first panel controls whether or not the other panels are visible. I did not do this with OOT because there were only 6 pretty straightforward …
> Panel UI refactor

- __init__.py
- fast64_internal/sm64/sm64_anim.py
- fast64_internal/sm64/sm64_geolayout_bone.py
- fast64_internal/sm64/sm64_geolayout_classes.py
- fast64_internal/sm64/sm64_geolayout_utility.py
- fast64_internal/sm64/sm64_geolayout_writer.py
- fast64_internal/utility.py
Also added general props for SM64 Bones.
So the new Custom Animated Bone.
It allows you to specify a bone's geo command macro, and defaults to `GEO_BONE`. The params are automatically filled out with layer, translation, rotation, and DL. a custom bone like this can reduce the number of matrix calculations in an armature by half, so a massive performance boost for those who use or create a custom geolayout command to work with this. I created one myself, and its currently in a [couple hacking sm64 repos](https://github.com/CrashOveride95/ultrasm64/pull/23)
> SM64 Added ability to use a custom animated bone

- fast64_internal/oot/oot_skeleton.py
fast64 uses a regex to detect and parse a skeleton header definition from C. The existing regex matches only old decomp formatting which is missing braces from the struct definition. The new regex matches both the old style and the new style.
> Fixed skeleton regex

- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/oot/oot_actor.py
- fast64_internal/oot/oot_f3d_writer.py
- fast64_internal/oot/oot_scene_room.py
- fast64_internal/oot/oot_skeleton.py
- fast64_internal/sm64/sm64_geolayout_bone.py
This begins a set of features for optimizing OoT skeletons. The optimizer can be turned on or off at skeleton export time; if it is off, the export process is like it has been in the past, and the assumptions below don't apply.
The optimizing features rely on maintaining state in the RSP and/or RDP between limbs of a skeleton. If optimization is enabled, drawing other DLs within the SkelAnime callbacks (OverrideLimbDraw or PostLimbDraw) will corrupt the graphics state. Limbs also can't be culled in software, though since there is no built-in culling mechanism, the user would have to write the culling themselves. (Actually, they can be culled, just very carefully.)
This PR provides one very basic optimization feature: not running the material setup DL when the material was already set up …
> Begin OoT skeleton optimizer

- fast64_internal/f3d/f3d_parser.py
This mainly affected Majora's Mask displaylists
> Fix bug that made some materials not be possible to import

- fast64_internal/oot/c_writer/oot_level_c.py
- fast64_internal/oot/c_writer/oot_segment_symbols_c.py
This change is being made since eventually `segment_symbols.h` will ideally be removed from decomp, and it makes more sense to just extern these within the scene file.
> Make OoT scene exporter include externs for room rom segments

- fast64_internal/f3d/f3d_writer.py
This pull request adds support for a "hack" that Majora's Mask does which allows you to have a texture that fills all of tmem (for example 32x64 rgba16) and load it into both Texel 0 and Texel 1. It is somewhat experimental but from the testing that I have done it seems to work. Essentially it just loads the texture into the same location in tmem for both texels.
> Add support for multitextures where both texels fill tmem

- fast64_internal/sm64/sm64_objects.py
Let users select two objects to use for instant warp offset instead of requiring manual entry.
> Instant Warp offset objects

- fast64_internal/oot/c_writer/oot_level_c.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/utility.py
This PR splits OoT scene and rooms files into multiple files based on their "data type." The types are as follows:
- Scene Main File (includes scene header, transition actor list, exit list, etc.)
- Scene Collision File (includes scene collision)
- Scene Texture File (includes material setup displaylists and textures that are shared between multiple rooms)
- Scene Cutscene File(s) (includes cutscene data, one file for each cutscene)
- Room Main File (includes room header, actor lists, etc.)
- Room Model Info File (contains the list of displaylists in a room)
- Room Model File (contains the room model and textures)
This is designed to make it easier to both read and modify scene or room files generated by Fast64, as well as be more consistent with how the vanilla scenes were split up. This …
> Make OoT scenes be split into multiple, modular files

- fast64_internal/oot/oot_f3d_writer.py
- fast64_internal/oot/oot_level_writer.py
Fixes the "expected 3, got 2" error when exporting skeletons and fixes the "no such file: dmadata.s" error when exporting scenes. Since decomp now automatically generates dmadata from spec, I've just commented modifyDmaMgrFileNames and modifyDmaTableEntries. It may be a good idea to fully oot_dma_manager_c later on down the road.
> Fix OoT skeleton export

- fast64_internal/oot/c_writer/oot_level_c.py
- fast64_internal/oot/c_writer/oot_spec.py
- fast64_internal/oot/oot_collision.py
- fast64_internal/oot/oot_level_classes.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_scene_room.py
- Rename "draw distance" to "fog far," because this is what the field is actually for.
- Fix a compiler warning in collision data
- Improve the formatting of collision data
- Made it so that multi-file scene export is compatible with the Export Scene button (no longer requires custom path)
> OoT Scene Export Cleanups

- fast64_internal/oot/oot_anim.py
- fast64_internal/oot/oot_skeleton.py
fast64 previously produced corrupted SkelAnime results when the mesh in Blender didn't have all the bones pointing the same direction in "rest position" (edit mode position). This was known as a "folded" skeleton because of the way imported meshes looked.
This issue was caused by the animation export code being overcomplicated and wrong. There is an explanation in the comments below of why the new version should work, so it's actually theoretically based, not just it happens to work.
This is tested and works with a complicated custom flex skel mesh which has many bones not pointing the same direction as well as with translation offsets. This has NOT yet been tested with creating custom animations on a mesh imported from the game. However, the changes made only impact the animation export …
> Support non folded skeletons

- fast64_internal/oot/c_writer/oot_level_c.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_scene_room.py
The code for making a list of all the cutscenes to be included in a scene was wrong, it ignored the main header and then exported duplicates of the main header cutscene for all other headers.
In the process I also realized that the "extra cutscenes" feature--to enable cutscene data to be included in a scene file, but not referenced from any scene header--could be used from any of the alternate scene headers. This is nonsense because the whole point is that these cutscenes are not associated with any header. So I've added code to ensure this feature is only usable from the main scene.
> Fix scene header confusion bug introduced in multi-file export changes

- fast64_internal/oot/oot_actor.py
- fast64_internal/oot/oot_level_classes.py
Previously, having actors only in some room headers did not work correctly. There was a syntax error caused by an omitted parameter, but even after fixing that, all actors were put in all room headers regardless of their settings. This was because the line `room.actorList = self.actorList` assigned the same `set` to all room headers, so that actors added to any of them would be added to all of them. It's not clear why the code was wrong like this, or why it uses a set in the first place; maybe someone should look at the corresponding SM64 code to see if that's also broken.
This commit also improves the GUI for custom header settings for actors, so that the grayed-out rows (for headers set to use previous headers) show the state of the referenced header, rather than showing the true value …
> Fix different actors per room header

- fast64_internal/f3d/f3d_gbi.py
- fast64_internal/f3d/f3d_writer.py
This PR aims to simplify material output when the Write All material method is used.
```
gsSPSetGeometryMode(G_SHADE | G_CULL_FRONT | G_SHADING_SMOOTH),
gsSPClearGeometryMode(G_ZBUFFER | G_CULL_BACK | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR),
```
now becomes
```
gsSPLoadGeometryMode(G_SHADE | G_CULL_FRONT | G_SHADING_SMOOTH),
```
> Make Fast64 use LoadGeometryMode when Write All material mode is used

- fast64_internal/f3d/f3d_gbi.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/sm64/sm64_objects.py
[issue 1: only objects in the first loaded scene were getting updated](https://canary.discord.com/channels/874816709855440926/874816710639767585/931351721232437249)
i was originally under the impression that changing scenes would run the persistent handlers, but its only when first loading a blend. so i changed iterating `bpy.context.scene.objects` to `bpy.data.objects`
[issue 2: combined bparams not matching the individuals](https://canary.discord.com/channels/874816709855440926/874816710639767585/931348767792332830)
My solution is to just _always_ derive combined bparams instead of storing it to another field
> deprecate combined_params - upgrade all objects in blend

- __init__.py
- fast64_internal/oot/c_writer/oot_level_c.py
- fast64_internal/oot/oot_level.py
- fast64_internal/oot/oot_level_classes.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_scene_room.py
This adds an option to OoT scene objects:
<details>
</details>
Diff between exporting with the option disabled and with the option enabled:
```diff
{ ACTOR_PLAYER, 0, -120, 0, 0, 0, 0, 0x0FFF },
};
-extern u8 _spot03_room_0SegmentRomStart[];
-extern u8 _spot03_room_0SegmentRomEnd[];
-
+// Dummy room list
RomFile spot03_scene_roomList[] = {
-	{ (u32)_spot03_room_0SegmentRomStart, (u32)_spot03_room_0SegmentRomEnd },
+	{0, 0},
};
EntranceEntry spot03_scene_header00_entranceList[] = {
```
The intent is to allow compiling the files separately (without linking) and then using the compiled files in tools such as zzrtl.
--------
The PR also introduces `Object.fast64.oot` and `Object.fast64.oot.scene`. Hopefully it doesn't break anything, I don't have much testing material
> [OoT] Add option to write a dummy room list

- fast64_internal/f3d/f3d_material.py
If using alpha compare threshold in two cycle mode, the alpha input it compares to is the combined alpha from the first cycle, not from the second cycle. The combined alpha value sent to the blender is still the correct combined alpha from the second cycle.
This is not described in the official SGI docs or anywhere else I have seen. In fact it is not mentioned that there is any way to get CC results from the first cycle while in two cycle mode.
Added labels warning users about this if they are using alpha compare threshold in two cycle mode.
> Add warning about RDP bug with alpha compare threshold

- fast64_internal/sm64/sm64_level_writer.py
in summary, `LOAD_MODEL_FROM_DL` was not getting retained between exports so exporting a level would delete those calls. it works nearly the same as `LOAD_MODEL_FROM_GEO` so i was able to join the logic together.
issue was posted here https://canary.discord.com/channels/874816709855440926/874818271378022450/951189088143306752
> added LOAD_MODEL_FROM_DL to retained level macros

- fast64_internal/sm64/sm64_geolayout_writer.py
more `lastMaterialName` misses 😔 i'm surprised this hasnt been encountered before yesterday
> fixed export bug by adding missing params to function call

- fast64_internal/f3d/f3d_material_nodes.py
Fixing #83
Looks like consequences of Blender fixing one or more bugs in Blender 3.1 maybe, potentially introducing another one I'm not sure
See my debug branch https://github.com/Dragorn421/fast64/commit/06179bf85470353a6beb9030e12be33d3b62fd92 for understanding what's printed below
---------
3.1 output
```
createTexCoordNode
<bpy_collection[2], NodeInputs> 2 ['', 'UV']
[bpy.data.node_groups['Create Tex Coord U F3D v3'].nodes["Group Output"].inputs[0], bpy.data.node_groups['Create Tex Coord U F3D v3'].nodes["Group Output"].inputs[1]]
<bpy_struct, NodeSocketVector("UV") at 0x7fba17462008>
UV <bpy_struct, NodeGroupOutput("Group Output") at 0x7fba17447e08>
node.name Group Output
type VECTOR
bl_idname NodeSocketVector
```
What's weird here is there are two input sockets to the output node, …
> Fix create F3D material error in Blender 3.1

- fast64_internal/oot/oot_collision.py
- fast64_internal/oot/oot_utility.py
See added comments in the code for what this fixes.
"1) The vertex with the minimum y coordinate should be first." is a previous fix that I moved
I also had to change `convertNormalizedFloatToShort` to return a signed value instead of unsigned to get a useful normal value to compare to. This "utility" function is only used by the modified collision export function and it seems like a good change in general anyway.
> [OoT] Fix vertex order in collision polygons

- __init__.py
- fast64_internal/oot/oot_anim.py
- fast64_internal/sm64/sm64_anim.py
- fast64_internal/utility_anim.py
Add a drop-down list option in the anim export panel, to pick what range of the exported animation to use.
I exported a basic animation with all three options for both OoT and SM64, seems to work on my end.
> Add `anim_range_choice` property

- __init__.py
Can't enable Fast64 anymore in Blender 3.1.0+ (raises an exception with an hopefully friendly enough message)
Any suggestion on the message?
Note: I can't test in Blender < 3.1.0 I hope this works as intended (do nothing) in those versions :cold_sweat:
> Prevent Fast64 from enabling in Blender 3.1.0+

- fast64_internal/oot/oot_skeleton.py
at some point (not recently) the `0xFF` value for "no limb next" was changed to use `LIMB_DONE`, somehow this hasn't been noticed earlier and as a result fast64 currently can't import oot skeletons
> Fix OoT skeleton import failing from `LIMB_DONE`

- fast64_internal/f3d/f3d_parser.py
Fixed bug where CI textures would be corrupted when importing OOT display lists.
> Fix incorrect CI textures on import for OOT

- __init__.py
For OOT, its easy to forget to set the F3D version to F3DEX2 when changing game modes, so it would be more convenient to auto set the F3D version when a game mode is selected.
> Auto set F3D version when game editor mode is set

- fast64_internal/utility.py
When working on a level, I was using boolean modifiers in order to create some intersecting geometry that I would be able to change on the fly. Turns out that is broken because the modifiers weren't applied to the original object position. This fixes that issue.
PRed to V5 to avoid more merge issues and V5 is imminent (right?)
> fixed exporting with modifiers that rely on other objects

- fast64_internal/oot/oot_constants.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_scene_room.py
I was thinking setting the room mode to "too hot" and using the heat timer might be confusing as it's hidden under Link Idle mode, this PR removes the 'too hot' entry from the idle enum and replaces it with a checkbox instead
Also I updated the room behavior enum names to be more accurate after doing some research with decomp
> [OoT] Minor room behavior improvements

- __init__.py
- fast64_internal/__init__.py
- fast64_internal/oot/__init__.py
- fast64_internal/oot/c_writer/oot_level_c.py
- fast64_internal/oot/c_writer/oot_scene_bootup.py
- fast64_internal/oot/c_writer/oot_scene_folder.py
- fast64_internal/oot/c_writer/oot_scene_table_c.py
- fast64_internal/oot/c_writer/oot_spec.py
- fast64_internal/oot/oot_actor.py
- fast64_internal/oot/oot_anim.py
- fast64_internal/oot/oot_collision.py
- fast64_internal/oot/oot_collision_classes.py
- fast64_internal/oot/oot_cutscene.py
- fast64_internal/oot/oot_f3d_writer.py
- fast64_internal/oot/oot_level.py
- fast64_internal/oot/oot_level_classes.py
- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_model_classes.py
- fast64_internal/oot/oot_operators.py
- fast64_internal/oot/oot_scene_room.py
- fast64_internal/oot/oot_skeleton.py
- fast64_internal/oot/oot_spline.py
- fast64_internal/oot/oot_utility.py
- fast64_internal/sm64/sm64_geolayout_constants.py
- fast64_internal/sm64/sm64_level_parser.py
- fast64_internal/sm64/sm64_rom_tweaks.py
Changes:
- Removed every ``from XXX import *`` from ``fast64_internal/oot`` (except the two useless files that gets deleted in #95) and other places where things broke
- Only import classes/functions/variables that are actually required
- Fixed missing imports where it was needed
Note that I'd love to do that with SM64 files but I don't know a thing about this game so I might break things on accident, though I still fixed some things here and there, same applies for F3D files
Also idk if the oot import is really required inside ``fast64_internal/__init__.py``
> [OoT] Imports cleanup

- fast64_internal/sm64/sm64_level_writer.py
This just checks up the tree from your currently selected object to see if it can be exported. Its pretty simple in functionality and the biggest convenience of this was actually being able to map a hotkey to the export level operator so that after i make changes i can just hit ctrl enter from my current object and it exports the whole level!
> [SM64] allow user to export a level from any of its children

- fast64_internal/oot/oot_level_writer.py
- fast64_internal/oot/oot_scene_room.py
A warning message appears instead in the object list panel if going over the limit.
> Removed object list limit for OOT

- fast64_internal/f3d/f3d_gbi.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/oot/oot_model_classes.py
- fast64_internal/sm64/sm64_f3d_writer.py
Flipbook texture handling now occurs right after a use_texture_reference texture is processed. This allows the TLUT loading commands to use the correct palette without having to be modified later on.
> [F3D] Flipbook CI textures no longer modify DLs after creation

- fast64_internal/oot/__init__.py
- fast64_internal/oot/oot_anim.py
- fast64_internal/oot/oot_collision.py
- fast64_internal/oot/oot_f3d_writer.py
- fast64_internal/oot/oot_skeleton.py
Instead of using a specified name in export settings, the name of the object is used instead. This applies to skeleton/DL/collision/animation exporters.
> Use object name for OOT exporters

- fast64_internal/f3d/f3d_gbi.py
Title says it all. This fixes a bug with the last change to gbi base classes which made them unhashable, and therefore unable to be added to sets/dicts: a function that is used in material overrides for armature exports.
The danger of this is that mutating the objects after they are stored inside a hashtable object is they will become unsearchable in these objects. An example is given here (from stack exchange)
```python
cat = Category('foo', 'bar') # a dataclass with unsafe_hash = True
categories = {cat}
cat.id = 'baz'
print(cat in categories)  # False
```
Alternate means of fixing this bug would be to create a base class implementation of `__hash__` that inherited from the `object` type. This has the benefit of maintaining state within hashtables if mutated, but not generating equal …
> [bugfix] add hashing to gbi base classes

- fast64_internal/oot/cutscene/properties.py
- fast64_internal/oot/oot_collision.py
- fast64_internal/oot/scene/exporter/to_c/scene_header.py
- fast64_internal/oot/scene/exporter/to_c/spec.py
Found and fixed 3 issues:
- Fast64 was still using ``LightSettings`` instead of the new type ``EnvLightSettings``, it was fine for normal decomp but on HackerOoT this was an issue as the old type has been removed
- Removed an extra argument inside the ``draw_props()`` function call from ``OOTCutsceneProperty.draw_props``, this was raising an error that didn't show the textbox UI elements for cutscenes
- Added missing ``_scene_`` chars to the filename exported in the spec file for cutscene files
> [OoT] Fixed 4 issues

- fast64_internal/f3d_material_converter.py
Blender bug apparently?? I guess this should slightly speed up material conversion anyways, but there's no reason why a vertex should be in a vertex group if the mesh itself doesnt have vertex groups
> Fixed issue while upgrading materials if a vert has groups but the mesh does not

- __init__.py
- fast64_internal/f3d/f3d_enums.py
- fast64_internal/f3d/f3d_material.py
Adds tooltips to the f3d material GUI for RDP settings. Tooltips are provided by the third argument in an enum item, or by the description key word argument to a property.
Tooltips can be viewed by hovering the mouse over the option in the GUI. The enums tooltips can be viewed by opening the enum and hovering the mouse over the given enum.
> [f3d] Material tooltips

- fast64_internal/f3d/f3d_parser.py
- fast64_internal/f3d/flipbook.py
- Address https://github.com/Fast-64/fast64/pull/194#discussion_r1181301139
- found a Blender 3.5 bug that messes with importing (uvs, normals, crashes). https://projects.blender.org/blender/blender/issues/107500
> Fix a mistake from a previous PR, and workaround for a Blender 3.5 bug related to uvs

- fast64_internal/f3d/f3d_gbi.py
updated the attribute name to fix, tested with exporting mario to a rom manager rom with success. To my knowledge no other low hanging binary export bugs exist.
> [bugfix] DPSetAlphaCompare Binary Export Fix

- fast64_internal/oot/scene/exporter/to_c/scene_table_c.py
Fixes a few issues with the scene-table parser:
- Handle empty lines (they produce empty `DEFINE_SCENE(` otherwise)
- Ignore single-line comments
- Ignore comments after the first data entry (they would be duplicated on save otherwise)
> [OoT] Scene-Table parser fix

- fast64_internal/f3d/f3d_bleed.py
- fast64_internal/f3d/f3d_gbi.py
- fast64_internal/f3d/f3d_parser.py
- fast64_internal/f3d/f3d_texture_writer.py
- fast64_internal/f3d/op_largetexture.py
- fast64_internal/sm64/sm64_geolayout_classes.py
- fast64_internal/sm64/sm64_geolayout_writer.py
I noticed some files had warnings that are easy to fix, so here it is
I'm not able to fix the one from [``sm64_f3d_writer.py``](https://github.com/Fast-64/fast64/blob/d97dcd22ad45f582e0a74f050ca5c17b7053d4da/fast64_internal/sm64/sm64_f3d_writer.py#L320) and the one from [``f3d_parser.py``](https://github.com/Fast-64/fast64/blob/d97dcd22ad45f582e0a74f050ca5c17b7053d4da/fast64_internal/f3d/f3d_parser.py#L2266), though for this one the class seems unused
About the change I did in ``f3d_gbi.py``, importing the class creates a circular import, so I thought it was better to remove the type hint and put a comment to clarify the type instead, not a great a solution but idk if it can work with the import
> Small Fixes 2

- fast64_internal/f3d/f3d_parser.py
- fast64_internal/f3d/f3d_writer.py
Vanilla SM64 uses a fixed direction of (0x28, 0x28, 0x28) for one directional light for the entire game (in camera space).
This vector is not normalized; its length is about 0.55f. However, F3D through F3DEX2 microcodes normalize light directions after transforming them, so it doesn't matter that this is too short. In contrast, F3DEX3 does not normalize light directions, because it transforms and normalizes vertex normals instead. So, this light direction being too short means that all the lighting is too dark.
The correctly normalized version of (0x28, 0x28, 0x28) is (0x49, 0x49, 0x49). This PR replaces this value. For projects using F3D - F3DEX2, this will change the exported data, but won't change the in-game appearance because the vector gets normalized anyway.
> Fix SM64 default light direction for F3DEX3 compatibility

- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_writer.py
Chroma key values were not referencing the correct prop path, and thus were not displaying properly, and also resulted in other props from not displaying.
To see issue, add chroma key scale or center to the combiner, and you will notice missing elements in the sources tab. If you open the console you will also see error messages. These issues are resolved in this PR.
> [F3D] Chroma Key F3D source display fix

- fast64_internal/oot/tools/operators.py
- fast64_internal/oot/tools/panel.py
- fast64_internal/oot/tools/quick_import.py
Add a "quick import" button, which allows to just put in a symbol name for it to be imported by fast64.
It can currently handle DLs, skeletons and animations
Just Works :tm:
> [OoT] Add Quick Import button

- fast64_internal/oot/props_panel_main.py
should fix the mario.blend error
> Check if parent object exists

- __init__.py
Can also use this PR to discuss the release (e.g. if we should wait for anything)
Yanies mentioned it may be good to wait for f3dex3 preview, but since that's not anywhere near ready afaik I think it's fine to have a release in between
It's been 2 years since the previous release :sweat_smile: 
If you have permission (I'm not sure who does) there is a release draft for 2.2.0 on the releases page https://github.com/Fast-64/fast64/releases (not visible by everyone apparently)
> Bump version to v2.2.0

- .github/workflows/black-lint.yml
- README.md
- pyproject.toml
Black 24 came out (for... 2024) and introduces a few changes. Let's just standardize on heavily-bugfixed 23 for now
See the README for updated instructions
I swear one day it will all be set up properly
> Use Black 23 specifically

- fast64_internal/oot/oot_upgrade.py
It was lacking a simple condition (and an import somehow)
> [OoT] Fixed door upgrade

- fast64_internal/f3d/f3d_writer.py
`if material_index >= len(material_slots):` (not sure how to reproduce a blend triggering this, I got one in DMs from someone)
`if material is None:` (slot without a material)
`if not material.is_f3d:` (material isn't f3d)
> Solidify checking materials assigned to faces

- __init__.py
- fast64_internal/f3d/f3d_material.py
Suggested by a ton of people.
Kinda of inconvenient for people who care about performance but with repo settings files (see settings rework pr) it will be no issue for anyone who cares.
> Prefer RGBA over CI toggle for automatic texture format

- fast64_internal/f3d/f3d_writer.py
Title
Normals are always calculated from version 4.1 onwards, making the use of `calc_normals_split()` unnecessary
> Blender Version 4.1 Fix

- fast64_internal/f3d/f3d_enums.py
I didn't delete my fork, you did
> Add Opaque (No AA, No Zbuf) to cycle2 render mode list 

- fast64_internal/oot/cutscene/classes.py
- fast64_internal/oot/cutscene/exporter/classes.py
Planning ahead for
https://github.com/zeldaret/oot/pull/1824
, breaking cutscene import/export due to different handling of floats
This just refactors reading/writing floats into `cs_import_float` and `cs_export_float` functions
Maybe the functions should be put together in a file but idk which?
> [OoT] Externalize cutscene float values export/import

- fast64_internal/f3d/f3d_material.py
simply preview vertex colors instead of lighting as a stopgap solution until support for previewing both is added
> preview vertex colors on packed materials (temporary solution)

- fast64_internal/f3d/f3d_parser.py
the goal of this pr is to fix when the argument is smaller then 1 (where -1 < 1 -1 equals false so he don't enter in the loop). I just change the while for a for loop.
> change the while with a for in parseMacroArgs

- fast64_internal/f3d/f3d_parser.py
cf https://developer.blender.org/docs/release_notes/4.1/python_api/
> use_auto_smooth is removed. [...] Meshes now always use custom normals if they exist.
> Fix OoT import failing in Blender 4.1

- fast64_internal/utility.py
Reported by TrevorBelmondo23, custom lights are not exported correctly, caused by corrupted indentation.
> Fixed bug with custom lights

- fast64_internal/sm64/sm64_objects.py
Export code was not accounting for the zxy order of object rotations (animations rotate xyz so they don't have this issue), this pr fixes that (see #320)
> [SM64] Fix object rotations

- fast64_internal/sm64/sm64_geolayout_writer.py
This issue is caused by reverts not being applied properly to all switch children. Basically only the last switch child got the revert, when it should be the last drawn one, and if it could be multiple different options, all of those should get a revert.
The first image is the bug in question, and the second is the one with fixes applied.
Mentioned in #331
> [SM64] Properly Apply DL Reverts to Last Drawn with Switch Nodes

- fast64_internal/sm64/sm64_objects.py
added sorting to object exports in sm64. Actors are sorted alphabetically. This will generally make it so the same type of object all export in a row since these will have names like: coin, coin.001, coin.002 etc.
> [SM64] Sort Level Objects Alphabetically

- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_writer.py
Fog now exports only when the `set_fog` boolean is checked and fog is used in the material, which is determined if `g_fog` is enabled, or if fog is an input to any of the blend variables. Previous behavior only checked if `set_fog` was on, which would mistakenly allow fog to be exported when the `set_fog` checkbox was invisible (and left checked from prev config) when material was changed to no longer have any fog inputs.
> [F3D] Fog Export Fix

- fast64_internal/sm64/sm64_objects.py
bug introduced in #339 woops lol.
I just did something simple here, the swap between quats and euler objects should be isomorphic (I can't actually prove this it has been a while since maths) so there is no loss in info.
> [SM64] Fixed Bug In Water Box Exports

- __init__.py
- fast64_internal/f3d/f3d_gbi.py
Game specific panels are hidden and `homebrew_compatible` type options are used while in that game mode.
> Added Homebrew Game Mode 

- __init__.py
- fast64_internal/f3d/f3d_material.py
- fast64_internal/utility.py
Whenever a material is created or edited, or a scene is loaded, this PR sets the Blender colorspace settings so that preview of vertex colors is accurate (or more accurate than otherwise).
> Automatically select correct colorspace

- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_material_presets.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/sm64/sm64_geolayout_bone.py
1. Moved culling into a new f3d model panel
2. Show default rdp world defaults in all game modes 
3. Use OOT's material presets for homebrew mode as they are versatile enough to be used in a homebrew context in my opinion, please comment on this
> [F3D] Homebrew Mode Improvements

- __init__.py
- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_material_helpers.py
- fast64_internal/f3d_material_converter.py
- fast64_internal/sm64/sm64_collision.py
- fast64_internal/utility.py
Changes:
1. Upgrades now copy over the current f3d library node tree onto the existing material, this has a lot of benifits such as no longer needing to purge materials, no naming changes, carying over all props, removal of hacks for material pointer propreties a̶n̶d̶ ̶t̶h̶e̶ ̶s̶p̶e̶e̶d̶ ̶o̶f̶ ̶u̶p̶g̶r̶a̶d̶e̶s̶  and on par speed (sometimes faster and sometimes slower?). Orphan data text is removed from upgrade popup.
2. Removed generateF3DNodeGraph.
3. Added warning for old materials and an early return for such.
4. Added "Recreate F3D Shader Nodes" operator, copies over the node tree from the f3d library and updates everything, useful for broken nodes of any kind.
5. Fixed f3d_light upgrading, along with now popping the props instead of just getting them.
6. Fixed …
> [F3D] Upgrade improvements (+related)

- fast64_internal/f3d/f3d_material.py
There was two options in fixing this:
Not exporting hidden modes or always showing all modes
I went with the latter in this pr as its more logical, nonsense example but if a game always defaults to packed normals but doesn´t default to lighting, that should still be setable AND visible in the world settings. Or maybe one could use a hack that revolves around checking for an unused mode being on. In my opinion this is the best way to do it and it doesn´t add much bloat to the UI even in ex3.
I also fixed a bug where if texgen was on without lighting it would still emulate texgen, even though it was neither visible or correct
> [F3D] Don´t hide properties that will get exported (specifically geo modes)

- fast64_internal/sm64/sm64_anim.py
Happened because of one fix before settings rework, code changed by the fix was never updated to use the new prop
> [SM64] Fix usage of sm64 scale in animations

- .gitignore
- fast64_internal/oot/oot_utility.py
- fast64_internal/oot/skeleton/importer/functions.py
- fast64_internal/oot/skeleton/utility.py
- scripts/oot/make_all_skeletons.py
- scripts/oot/make_skeletons.py
The Majora's Mask decomp uses limb enums on their assets, which changes the generated .c files for objects enough that skeletons won't import. This patch series adds a script to check how many files import skeletons from a decomp folder (currently only 3/176 or 1.7% successful) and adds handling for parsing these limb enums and using their when adding limbs. After these changes, 166/174 (95.4%) import skeletons without throwing exceptions.
I did most of my manual testing by:
1. Open blender
1. In Fast64, set the game to OOT
1. In the OOT settings under OOT File Settings, set the decomp path to a checkout of the Majora's Mask decomp (with `make setup` complete) so assets are extracted
1. Under the `OOT Skeleton Exporter` section, import a skeleton from the MM decomp.
1. I typically tested …
> Support ZAPD bone enums for skeleton import

- fast64_internal/f3d/f3d_bleed.py
- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_texture_writer.py
- fast64_internal/f3d/f3d_writer.py
The mode is still automatically set when using CI textures, however the default can now be changed and it hides what's happening under the hood just a bit less,  I also removed some code from f3d_bleed, specifically I removed reset_command_dict (unused) and DPSetTextureLUT from the cmd list in add_reset_cmd because it is always set by SPSetOtherMode like other othermodes.
> [F3D] Show tlut othermode in materials and world defaults

- fast64_internal/f3d/f3d_material.py
Fixes preview of fogshade with no fog geo mode enabled
> [F3D] Pass in shade alpha into fog blender instead of disabling it when fog is off

- fast64_internal/oot/tools/quick_import.py
The Quick Import feature works by scanning assets files for symbols, first roughly with just `sym_name in source`, then accurately with a regex if the rough check passed.
However if the first rough check passed, the file was wrongly recorded as having the symbol even if the regex found no match.
This PR fixes this problem.
> [OoT] Fixup Quick Import

- fast64_internal/oot/exporter/room/header.py
- fast64_internal/oot/oot_utility.py
to test this, get a blend with two rooms (or more) and have an actor in each room (one or several), then make sure the exported data is correct (works for me)
> [OoT] Fixed actors exported in several rooms

- fast64_internal/f3d/f3d_gbi.py
Add size() of 2 for SPAmbOcclusion and SPLightColor, fixes SPPerspNormalize in ex3, DPSetOtherMode and DPSetTileSize.is_LOADTILE (was that one ever used?).
Also cleans up SPSetOtherMode to use getattr default instead of checking with hasattr.
> [F3D] Fix issues in the GBI macros

- fast64_internal/f3d/f3d_parser.py
When importing a scene that references `gMtxClear` (ex. inside Jabu Jabu), currently the code fails since `F3DContext.createMesh()` clears out old matrix data. This fixes that.
> Fix gMtxClear reference for OOT scene importing

- fast64_internal/utility.py
It is not enough to rely on an object's location and rotation as we need a relative position.
[broken graphics parented.blend.zip](https://github.com/user-attachments/files/16657743/broken.graphics.parented.blend.zip)
[Code diff](https://github.com/Lilaa3/sm64/commit/321dedfe3d4d114e0f32cf28343e67f9b76d4069)
> [SM64] Fix #352 regression

- fast64_internal/oot/props_panel_main.py
- fast64_internal/oot/room/properties.py
Changes some text labels that might be misleading. 
This one only shows up when you select the Cullable room type which leads you to believe it sets up CPU culling automatically. It doesn't. The only thing fast64 sets up automatically is RSP culling, and it does so regardless of whether the room type is "Cullable" or "Normal".
Therefore I changed it to: 
This text which shows up when you select  "Custom Cull Group" empty type is also misleading. It can lead the user to believe that what they're doing is unnecessary since fast64 is already doing it:
So I changed it to:
> [UI] [OOT] More informative text regarding culling

- fast64_internal/sm64/sm64_level_writer.py
macros were parsing comments even though they were on a new line, so I made the macro not see a comment with a newline character unless there was a backslash
> [SM64] Fix persistent block spam

- __init__.py
Noticed that when kaze updated his microcode was set when it shouldn´t have, this is bad but we need to update existing world defaults nonetheless, added repo settings load to make this even less of an issue, pre-release should update the decomp path causing the path to be correct as well (if there is a repo file of course)
> more conservative game editor update

- fast64_internal/sm64/sm64_objects.py
currently the `LOAD_MODEL_FROM_GEO` command gets written incorrectly, before the segment load commands. The game will compile, but crashes.
> [SM64] fix exporting the levels/scripts.c write for common1 and group0

- __init__.py
- fast64_internal/repo_settings.py
- fast64_internal/sm64/settings/panels.py
- fast64_internal/sm64/settings/properties.py
- fast64_internal/sm64/settings/repo_settings.py
- fast64_internal/utility.py
Fixes lag at start up from draw layers being set unnecessarily. Some clean up that I already did in #461
> [Repo Settings] Only set if different

- fast64_internal/sm64/settings/properties.py
- fast64_internal/sm64/sm64_geolayout_writer.py
- fast64_internal/sm64/sm64_objects.py
- fast64_internal/utility.py
Fixes #463
Old property was hidden post combined export pr, this adds a new prop for it in the combined exporter and upgrades it
> [SM64] Add back custom include directory + add automatic option

- fast64_internal/oot/cutscene/constants.py
- fast64_internal/oot/cutscene/exporter/classes.py
- fast64_internal/oot/cutscene/importer/classes.py
- fast64_internal/oot/cutscene/operators.py
- fast64_internal/oot/cutscene_docs.md
- fast64_internal/oot/exporter/cutscene/__init__.py
Find and replace PR + updated the descriptions to align with what decomp has.
Fixes compatibility issues introduced by https://github.com/zeldaret/oot/pull/2311
> [OoT] Update cutscene macro names

- fast64_internal/f3d/f3d_texture_writer.py
- fast64_internal/f3d/f3d_writer.py
- fast64_internal/oot/exporter/scene/__init__.py
- fast64_internal/oot/exporter/scene/general.py
- fast64_internal/utility.py
I thought of wrapping saveOrGetF3DMaterial as well (with a decorator since it's used in multiple places) to avoid these kind of empty errors in the future, I'm fine with reverting that tho I think it is for the better (in ac I wanted to throw errors where the material wasn't in the args already and it's very annoying, this way everything is consistent)
> [OOT + F3D] More informative error messages for deleted lights

- fast64_internal/sm64/c_templates/tile_scroll.py
Only took me 3 years to finally address this lol
> SM64: Add missing typecasts from Gfx* to SetTileSize* to suppress compiler warnings

- fast64_internal/f3d/f3d_bleed.py
In the offending function, materials were checked for any "DP" type gbi macro, and if there were none, the pipe sync was removed. The issue with this is that the DL for tesxture loading was a separate GfxList, so pipe syncs were removed if textures were loaded by no material changes occured.
> [F3D] [Bugfix] Fix Sync Optimization for Mat Bleed

- fast64_internal/sm64/sm64_f3d_writer.py
- Add bleed and inline support.
- Assert for fmeshes len
- No longer use getDrawLayerV3, yes it doesn´t matter here but it was the last bit of code to use it, with permission I'd like to remove the function
> [SM64] Bring binary dl exporter up-to-date

- fast64_internal/f3d/f3d_gbi.py
- fast64_internal/f3d/f3d_material.py
- fast64_internal/f3d/f3d_texture_writer.py
- fast64_internal/sm64/sm64_f3d_writer.py
- fast64_internal/utility.py
Fixes #451 
- Updated: Tex prop is now drawn using ui_image, ui_image has been updated to optionally hide low and high props (are handled by size cmd, does not exist for texture rectangles) 
- materialless_setup func for TexInfo, equivelant to moreSetupFromModel for bpy material-less contexts, obviously cannot handle flipbooks 
- setup_single_tex func for TexInfo, sets up a single texture without the context of the multi texture manager
- ignore_tex_set bool for fromProp
- Use only fromProp and updated writeAll
- Use saveModeSetting (and world defaults) instead of manullay appending each DP command (except for blend color)
- Removed syncs except for the sync after the texrect cmd to do the reverts
- Removed deprecated arg for png exporting in save_textures (assumed from fimage)
- Removed …
> [SM64/F3D] Fix and update Ui Image Exporter

- fast64_internal/oot/actor/properties.py
currently if an actor is using an enum in its data it will ignore the actor's type value, this PR fix this issue (hopefully that's the only major issue in the actor panel :pray: )
> [OoT] Fixed actor enums overriding actor types

- fast64_internal/oot/f3d/operators.py
- fast64_internal/oot/f3d/properties.py
- fast64_internal/oot/oot_f3d_writer.py
- fast64_internal/oot/skeleton/importer/functions.py
- fast64_internal/oot/skeleton/properties.py
it was mentioned on discord how annoying the value 100 is when exporting actor stuff, this PR change that to 10 (which was the recommended value), also another change: if the auto-detect don't return a value it will default the scale to the one from the `actorScale` value (which is now 10 by default)
discord discussion: https://discord.com/channels/874816709855440926/874819026629574717/1353518470808997980
> [OoT] Update actor scale's default value

- fast64_internal/sm64/sm64_collision.py
- fast64_internal/sm64/sm64_geolayout_writer.py
- fast64_internal/sm64/sm64_objects.py
- fast64_internal/utility.py
Typically when exporting all selected with the combined exporter, exceptions were passed over as it would be common for objects to be selected without gfx or col data and to throw an exception.
Now the exceptions I except to appear during this have an extra argument that I catch during exception processing so that I only pass them (e.g. no data type exceptions), and all other valid exceptions will halt the export
> [SM64] Add better exception processing to combined exporter

- fast64_internal/oot/cutscene/operators.py
The operator wasn't using ``Cutscene.new()``, resulting in export issues
> [OoT] Fixed standalone cutscene export

- fast64_internal/oot/exporter/decomp_edit/spec.py
Recently decomp changed how the spec file is handled, now there's a split for scenes and overlays (also other files that we don't care here), the `spec` file at the root turned to a folder, which contains the spec file with the includes I mentioned. With this fix it should work properly for both legacy and new decomps (untested for legacy). Also there was an issue where the stuff before the first segment would be misinterpreted if it's not present (which is the case for the scene spec includes).
Note: while it should work properly for normal decomp, it's still broken for HackerOoT specifically because of an `#else` in the scene table
> [OoT] Fixed writing to the spec file

- fast64_internal/oot/cutscene/operators.py
- fast64_internal/oot/exporter/cutscene/actor_cue.py
- fast64_internal/oot/exporter/cutscene/camera.py
- fast64_internal/oot/exporter/cutscene/data.py
- fast64_internal/oot/exporter/scene/__init__.py
Addresses #526 and #527, I added 3 missing includes and make camera points use `DEG_TO_BINANG` to fix compile issues with IDO (I tested and it seems to work properly now), also I noticed `getOoTRotation` was exporting floats as doubles I think so I fixed that too (though it probably doesn't matter because of the macro but it bothered me)
> [OoT] Scene/Cutscene Export Fixes

- fast64_internal/oot/cutscene/motion/operators.py
- fast64_internal/oot/cutscene/motion/properties.py
- fast64_internal/oot/cutscene/motion/utility.py
Add buttons to move cutscene bones around in OoT cutscenes, since the exporter (and preview *as of this PR*) use them in the order they're displayed in.
Note rather than being actually *moved*, the bones are deleted and re-created
screenshot:
<details>
</details>
> [OoT] Add move cutscene bone operator

- fast64_internal/oot/oot_f3d_writer.py
Before, texture arrays were written after the includes (because the addon couldn't find the arrays to edit):
```diff
diff --git a/src/code/z_player_lib.c b/src/code/z_player_lib.c
index 1ac27fdb6..d047f898a 100644
--- a/src/code/z_player_lib.c
+++ b/src/code/z_player_lib.c
@@ -16,6 +16,34 @@
#include "assets/objects/gameplay_keep/gameplay_keep.h"
#include "assets/objects/object_link_boy/object_link_boy.h"
#include "assets/objects/object_link_child/object_link_child.h"
+{     gLinkAdultSkel_mouth_closed_ci8_png_001_ci8,
+    gLinkAdultSkel_mouth_half_ci8_png_001_ci8,
+    gLinkAdultSkel_mouth_open_ci8_png_001_ci8,
+    gLinkAdultSkel_mouth_smile_ci8_png_001_ci8,
+ }
+{     gLinkAdultSkel_eyes_open_ci8_png_001_ci8,
+    gLinkAdultSkel_eyes_half_ci8_png_001_ci8,
+ …
```
> [OoT] Fix player flipbooks export

- fast64_internal/oot/exporter/__init__.py
- fast64_internal/oot/exporter/room/__init__.py
- fast64_internal/oot/exporter/scene/__init__.py
- fast64_internal/oot/exporter/scene/rooms.py
- fast64_internal/oot/oot_object.py
We missed a little bug with the exporter, when you export actors without their object dependencies, Fast64 will add it automatically, except since the new exporter it was being added to the duplicated room object instead of the original room object
This is addressed by passing the original scene object to `RoomEntries.new()` which will fetch the original room objects to use in `addMissingObjectsToAllRoomHeaders`, not sure if there's a better fix but this works
> [OoT] Fixed object being added to the duplicated room object

- fast64_internal/oot/animation/operators.py
Currently the animation exporter assumes you never use a custom path, which can raise an error with `No name entered for the exporter.` if the object name happens to be empty, this PR addresses that issue
> [OoT] Fix animation exporter expecting an object name with custom paths

- fast64_internal/oot/exporter/collision/__init__.py
- fast64_internal/oot/exporter/collision/surface.py
custom conveyor speeds can be strings, as returned by `Utility.getPropValue(colProp, "conveyorSpeed")`, but fast64:main always passes it to `int(*, base=16)` which fails on non-hex strings. this PR only uses `int()` on non-custom `conveyorSpeed`s
> Fix export of custom conveyorSpeed

- fast64_internal/z64/exporter/cutscene/__init__.py
- fixes an issue where extra cutscenes couldn't be exported
- ~~added a check to check if the path exists for the standalone exporter, for some reasons relative paths are broken for me but it makes no sense at all, I don't see why it wouldn't work but absolute paths works properly~~ actually no forget about that I'm dumb
> [OoT] Fix cutscene export issues

- fast64_internal/sm64/sm64_constants.py
- fast64_internal/sm64/sm64_level_writer.py
- fast64_internal/sm64/sm64_objects.py
- Adds segment 8 group loads (common0)
- Global "Write Actor Loads" checkbox instead of individual "Do Not Write" options for each segment. If disabled (default) it will export the same exact loads that are already present in the script. If enabled, it will replace the loads with the groups that are selected in Fast 64.
- "Do not write" is replaced with a "None" option for each segment load. If set to none, will remove any existing loads for this segment that are already present in the script.
One of the issues with how actor loads are handled in the current system is that it will only ever replace the actor load `JUMP_LINK` commands that already exist. So for instance if a segment 6 group isn't loaded in the original level script, Fast 64 will not add the correct `JUMP_LINK` command …
> [SM64] Rework actor load exports for level scripts

- README.md
The README.md for the repo still points to the old `/fast64_internal/oot/README.md` path for Ocarina of Time documentation, which was changed in #540. This fixes the README.md so that it now points to the correct Ocarina of Time documentation path `/fast64_internal/z64/README.md`.
> Fix README link for Ocarina of Time to point to z64 folder

- fast64_internal/utility.py
the remade version of set origin was not equivalent to the previous one, breaking SM64. we were applying -target_loc instead of the offset between target loc and the original location
> [Codebase] Restore original functionality to setOrigin
